language: go
sudo: false
go:
  - 1.6
env:
  global:
    - GO15VENDOREXPERIMENT=1

before_install:
  - sudo apt-get install -y rpm

install:
  - go get github.com/golang/lint/golint
  - go get github.com/Masterminds/glide
  - make vendor-update

script:
  - make rpm

notifications:
  email:
    recipients:
      - nthomas@redhat.com
      - shtripat@redhat.com
    on_success: change
    on_failure: always
